#!/bin/bash
# ============================================
# Bash System Health Checker
# Uses variables, conditionals, loops, pipes
# ============================================

# 1. Input
echo "Enter your name to start the report:"
read user_name
echo "Generating report for $user_name..."
echo "-----------------------------------"

# 2. Absolute log path (safe for cron)
LOG_DIR="$HOME/logs"
mkdir -p "$LOG_DIR"
HEALTH_LOG="$LOG_DIR/health_report.log"

# Clear log from previous run
> "$HEALTH_LOG"

# 3. Write report into log file
{
echo "=========================================="
echo "  SYSTEM HEALTH REPORT"
echo "  Generated by: $user_name"
echo "  Date/Time:    $(date)"
echo "  Hostname:     $(hostname)"
echo "  Running as:   $(whoami)"
echo "=========================================="

# 4. Disk Space Check
echo ""
echo "[ DISK USAGE ]"
usage=$(df / | awk 'NR==2 {print $5}' | tr -d '%')
if [ "$usage" -gt 80 ]; then
    echo "  ALERT: Disk usage is HIGH ($usage%)! Consider freeing space."
elif [ "$usage" -gt 60 ]; then
    echo "  WARNING: Disk usage is moderate ($usage%)."
else
    echo "  OK: Disk usage is healthy ($usage%)."
fi
df -h / | awk 'NR==2 {printf "  Used: %s / Total: %s / Available: %s\n", $3, $2, $4}'

# 5. Memory Check
echo ""
echo "[ MEMORY USAGE ]"
free -h | awk 'NR==2 {printf "  Used: %s / Total: %s / Free: %s\n", $3, $2, $4}'

# 6. CPU Load
echo ""
echo "[ CPU LOAD AVERAGES (1m / 5m / 15m) ]"
uptime | awk -F'load average:' '{ print "  " $2 }'

# 7. Top 5 Memory-Consuming Processes
echo ""
echo "[ TOP 5 PROCESSES BY MEMORY ]"
ps aux --sort=-%mem | awk 'NR==1{printf "  %-10s %-6s %-6s %s\n", "USER","PID","%MEM","COMMAND"} NR>1 && NR<=6{printf "  %-10s %-6s %-6s %s\n", $1,$2,$4,$11}'

# 8. Top 3 CPU-Consuming Processes
echo ""
echo "[ TOP 3 PROCESSES BY CPU ]"
ps -eo pcpu,pid,comm --sort=-pcpu | awk 'NR==1{printf "  %-8s %-8s %s\n", "%CPU","PID","COMMAND"} NR>1 && NR<=4{printf "  %-8s %-8s %s\n", $1,$2,$3}'

# 9. Uptime
echo ""
echo "[ SYSTEM UPTIME ]"
uptime -p | awk '{print "  " $0}'

echo ""
echo "=========================================="
echo "  END OF REPORT"
echo "=========================================="

} >> "$HEALTH_LOG"

# 10. Print to screen and confirm log location
cat "$HEALTH_LOG"
echo ""
echo "-----------------------------------"
echo "Report complete! Log saved to:"
echo "  $HEALTH_LOG"
echo "-----------------------------------"