#!/bin/bash
# ============================================
# Bash System Health Checker
# Compatible with macOS and Linux
# ============================================

# 1. Input
echo "Enter your name to start the report:"
read user_name
echo "Generating report for $user_name..."
echo "-----------------------------------"

# 2. Absolute log path (safe for cron)
LOG_DIR="$HOME/logs"
mkdir -p "$LOG_DIR"
HEALTH_LOG="$LOG_DIR/health_report.log"

# Detect OS once
OS="$(uname -s)"

# Clear log from previous run
> "$HEALTH_LOG"

{
echo "=========================================="
echo "  SYSTEM HEALTH REPORT"
echo "  Generated by: $user_name"
echo "  Date/Time:    $(date)"
echo "  Hostname:     $(hostname)"
echo "  Running as:   $(whoami)"
echo "  OS:           $OS"
echo "=========================================="

# 4. Disk Space Check
echo ""
echo "[ DISK USAGE ]"
usage=$(df / | awk 'NR==2 {print $5}' | tr -d '%')
if [ "$usage" -gt 80 ]; then
    echo "  ALERT: Disk usage is HIGH ($usage%)! Consider freeing space."
elif [ "$usage" -gt 60 ]; then
    echo "  WARNING: Disk usage is moderate ($usage%)."
else
    echo "  OK: Disk usage is healthy ($usage%)."
fi
df -h / | awk 'NR==2 {printf "  Used: %s / Total: %s / Available: %s\n", $3, $2, $4}'

# 5. Memory Check (macOS uses vm_stat instead of free)
echo ""
echo "[ MEMORY USAGE ]"
if [ "$OS" = "Darwin" ]; then
    page_size=$(pagesize)
    pages_free=$(vm_stat | awk '/Pages free/ {print $3}' | tr -d '.')
    pages_speculative=$(vm_stat | awk '/Pages speculative/ {print $3}' | tr -d '.')
    pages_active=$(vm_stat | awk '/Pages active/ {print $3}' | tr -d '.')
    pages_inactive=$(vm_stat | awk '/Pages inactive/ {print $3}' | tr -d '.')
    pages_wired=$(vm_stat | awk '/Pages wired/ {print $4}' | tr -d '.')
    pages_compressed=$(vm_stat | awk '/Pages occupied by compressor/ {print $5}' | tr -d '.')

    used_bytes=$(( (pages_active + pages_wired + pages_compressed) * page_size ))
    free_bytes=$(( (pages_free + pages_speculative + pages_inactive) * page_size ))
    total_bytes=$(( used_bytes + free_bytes ))

    used_gb=$(echo "scale=1; $used_bytes / 1073741824" | bc)
    free_gb=$(echo "scale=1; $free_bytes / 1073741824" | bc)
    total_gb=$(echo "scale=1; $total_bytes / 1073741824" | bc)

    echo "  Used: ${used_gb}GB / Total: ${total_gb}GB / Free: ${free_gb}GB"
else
    free -h | awk 'NR==2 {printf "  Used: %s / Total: %s / Free: %s\n", $3, $2, $4}'
fi

# 6. CPU Load Averages
echo ""
echo "[ CPU LOAD AVERAGES (1m / 5m / 15m) ]"
if [ "$OS" = "Darwin" ]; then
    uptime | awk -F'load averages:' '{ print "  " $2 }'
else
    uptime | awk -F'load average:' '{ print "  " $2 }'
fi

# 7. Top 5 Processes by Memory
echo ""
echo "[ TOP 5 PROCESSES BY MEMORY ]"
if [ "$OS" = "Darwin" ]; then
    ps aux -m | awk 'NR==1{printf "  %-10s %-6s %-6s %s\n","USER","PID","%MEM","COMMAND"} NR>1 && NR<=6{printf "  %-10s %-6s %-6s %s\n",$1,$2,$4,$11}'
else
    ps aux --sort=-%mem | awk 'NR==1{printf "  %-10s %-6s %-6s %s\n","USER","PID","%MEM","COMMAND"} NR>1 && NR<=6{printf "  %-10s %-6s %-6s %s\n",$1,$2,$4,$11}'
fi

# 8. Top 3 Processes by CPU
echo ""
echo "[ TOP 3 PROCESSES BY CPU ]"
if [ "$OS" = "Darwin" ]; then
    ps aux -r | awk 'NR==1{printf "  %-8s %-8s %s\n","%CPU","PID","COMMAND"} NR>1 && NR<=4{printf "  %-8s %-8s %s\n",$3,$2,$11}'
else
    ps -eo pcpu,pid,comm --sort=-pcpu | awk 'NR==1{printf "  %-8s %-8s %s\n","%CPU","PID","COMMAND"} NR>1 && NR<=4{printf "  %-8s %-8s %s\n",$1,$2,$3}'
fi

# 9. Uptime
echo ""
echo "[ SYSTEM UPTIME ]"
if [ "$OS" = "Darwin" ]; then
    uptime | awk '{print "  " $0}'
else
    uptime -p | awk '{print "  " $0}'
fi

echo ""
echo "=========================================="
echo "  END OF REPORT"
echo "=========================================="

} >> "$HEALTH_LOG"

cat "$HEALTH_LOG"
echo ""
echo "-----------------------------------"
echo "Report complete! Log saved to:"
echo "  $HEALTH_LOG"
echo "-----------------------------------"